spring.application.name=SQLCatalog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url= jdbc:postgresql://localhost:5432/SQLCatalog
spring.datasource.username=postgres
spring.datasource.password=818520
