spring.application.name=SQLCatalog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url= jdbc:postgresql://localhost:5432/SQLCatalog
spring.datasource.username=postgres
spring.datasource.password=818520
jwt.secret=v76X39,G}V0RY5W_D!$J0OL31std2O4L
jwt.expiration=86400000
